
# ------------------------------------------------------------
# Training Configuration
# ------------------------------------------------------------

training:


  split:

    test_size: 0.20

    shuffle: true

    stratify: true

# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

  preprocessing:

    numerical:

      scaler: StandardScaler

      parameters:
        with_mean: true
        with_std: true


    categorical:

      encoder: OneHotEncoder

      parameters:
        handle_unknown: ignore
        sparse_output: false
        drop: first


  # ----------------------------------------------------------
  # Class Imbalance / Sampling
  # ----------------------------------------------------------

  sampling:

    enabled: true

    method: smotenc

